package com.xltechnologie.entities;
// Generated 2018-11-05 17:37:51 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Table;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "category",
        catalog = "dbo"
)
@NamedQueries({
    @NamedQuery(
            name = "selectAllAccount",
            query = "from Account a"
    )
})

public class Account implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID")
    private long id;
    @Column(name = "CardNumber")
    private Integer cardNumber;
    
    @ManyToMany(mappedBy = "Account")
    private Set<Member> members = new HashSet<>();

    @OneToMany(mappedBy="Account")
    private Set <Invoice> spendings = new HashSet(0);


    public Account() {
    }

    public Account(long id) {
        this.id = id;
    }

    public Account(long id, Integer cardNumber, Set spendings, Set members) {
        this.id = id;
        this.cardNumber = cardNumber;
        this.spendings = spendings;
        this.members = members;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Integer getCardNumber() {
        return this.cardNumber;
    }

    public void setCardNumber(Integer cardNumber) {
        this.cardNumber = cardNumber;
    }

    public Set getSpendings() {
        return this.spendings;
    }

    public void setSpendings(Set spendings) {
        this.spendings = spendings;
    }

    public Set getMembers() {
        return this.members;
    }

    public void setMembers(Set members) {
        this.members = members;
    }

}
