package com.xltechnologie.entities;
// Generated 2018-11-21 20:09:49 by Hibernate Tools 4.3.1

import com.xltechnologie.dao.CategoryDAO;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category",
        catalog = "dbo"
)
@NamedQueries({
    @NamedQuery(
            name = "selectAllCategory",
            query = "from Category c"
    )
})

public class Category implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private long id;
    @Column(name = "name")
    private String name;
    @ManyToMany(mappedBy = "categories")
    private Set<Store> stores = new HashSet<>();

    public Category() {
    }

    public Category(long id, String name) {
        this.id = id;
        this.name = name;
    }

    public Category(String name) {
        this.name = name;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<Store> getStores() {
        return stores;
    }

    public void setStores(Set<Store> stores) {
        this.stores = stores;
    }

    @Override
    public String toString() {
        return "Category{" + "id=" + id + ", name=" + name + ", stores=" + stores + '}';
    }
}
